---
defaults:

- scope:
    path: ''
  values:
    layout: default

- scope:
    type: posts
    path: gigs
  values:
    layout: gig
    priority: 100

- scope:
    type: albums
  values:
    layout: album

- scope:
    type: posts
    path: blog

  values:
    priority: 100

collections:
  albums:
    output: true

permalink: pretty
future: true
