---
defaults:

- scope:
    path: ''
  values:
    layout: default

- scope:
    type: posts
    path: gigs
  values:
    layout: gig
    pretitle: |
      <a
        href='/gigs'
        >
        Gigs
      </a>
      »

- scope:
    type: albums
  values:
    layout: album
    pretitle: |
      <a
        href='/albums'
        >
        Albums
      </a>
      »

- scope:
    type: posts
    path: blog
  values:
    layout: blost
    priority: 100

collections:
  albums:
    output: true

permalink: pretty
future: true

url: https://rawfunkmaharishi.uk
exclude:
  - scripts
  - spec
include:
  - .well-known
